#numpy:
#  - 1.19
numpy:
  # python 3.7-3.9
  - 1.19    # [not (osx and arm64)]
  - 1.19    # [not (osx and arm64)]
  - 1.19    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
