{% set version="0.20.1" %}

package:
  name: pandas
  version: {{ version }}

source:
  fn: pandas-{{ version }}.tar.gz
  url: https://github.com/pydata/pandas/archive/v{{ version }}.tar.gz
  sha256: e0613cb3847d5e0eecf4735e067835c34f41c2f4b6e8d2f5ef01acd28db74c39

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy  x.x
  run:
    - python
    - numpy  x.x
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX pandas  # [not win]
    - conda inspect objects -p $PREFIX pandas  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
