{% set name = "pandas" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas-{{ version }}.tar.gz
  sha256: 4f18ba62b61d7e192368b84517265a99b4d7ee8912f8708660fb4a366cc82667

build:
  number: 0
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - python-build
    - meson-python ==0.13.1
    - meson ==1.2.1
    - cython >=3.0.5,<4
    - numpy >=1.22,<2.0  # [py<310]
    - numpy >=2.0,<2.3  # [py>=310]
    - versioneer
    - pip
  run:
    - python
    # Base Dependencies
    - numpy >=1.22,<2.0  # [py<310]
    - numpy >=2.0,<2.3  # [py>=310]
    - python-dateutil >=2.8.2
    - pytz >=2020.1
    - python-tzdata >=2022.7
    # Recommended dependencies to achieve large speedups
    # see https://pandas.pydata.org/pandas-docs/version/2.1.1/getting_started/install.html#performance-dependencies-recommended
    - numexpr >=2.8.4
    - bottleneck >=1.3.6
  run_constrained:
    # Optional dependencies
    # see https://pandas.pydata.org/pandas-docs/version/2.1.1/getting_started/install.html#optional-dependencies
    # and https://github.com/pandas-dev/pandas/blob/v2.1.1/pyproject.toml
    # performance
    - numba >=0.56.4
    # plot
    - matplotlib-base >=3.6.3
    # output_formatting
    - jinja2 >=3.1.2
    - tabulate >=0.9.0
    # computation
    - scipy >=1.10.0
    - xarray >=2022.12.0
    # fss
    - fsspec >=2022.11.0
    # aws
    - s3fs >=2022.11.0
    # gcp
    - gcsfs >=2022.11.0
    - pandas-gbq >=0.19.0
    # excel
    - odfpy>=1.4.1
    - openpyxl >=3.1.0
    - python-calamine >=0.1.7
    - pyxlsb >=1.0.10
    - xlrd >=2.0.1
    - xlsxwriter >=3.0.5
    # parquet, feather
    - pyarrow >=10.0.1
    # hdf5
    - blosc >=1.21.3
    - pytables >=3.8.0
    # spss
    - pyreadstat >=1.2.0
    # DB
    - sqlalchemy >=2.0.0
    - psycopg2 >=2.9.6
    - pymysql >=1.0.2
    - adbc-driver-postgresql >=0.8.0
    - adbc-driver-sqlite >=0.8.0
    # html, xml
    - beautifulsoup4 >=4.11.2
    - html5lib >=1.1
    - lxml >=4.9.2
    # compression
    - zstandard >=0.19.0
    # clipboard
    - pyqt >=5.15.9
    - qtpy >=2.3.0
    # consortium-standard
    - dataframe-api-compat >=0.1.7
    # uncategorized
    - fastparquet >=2022.12.0
test:
  requires:
    - pip
    - pytest >=7.3.2
    - pytest-xdist >=2.2.0
    - hypothesis >=6.46.1
  commands:
    - pip check
    {% set config_path = "{{ SRC_DIR }}/pyproject.toml" %}
    {% set markers = ["not clipboard", "not single_cpu", "not slow", "not network", "not db"] %}
    {% set markers = markers + ["not arm_slow"] %}   # [aarch64 or ppc64le]
    {% set extra_args = ["-m " + " and ".join(markers)] %}
    {% set extra_args = extra_args + ["-n=2"] %}
    {% set tests_to_skip = "_not_a_real_test" %}
    {% set tests_to_skip = tests_to_skip + " or test_can_set_locale_valid_set" %}                 # [osx]
    # skiptest_rolling_var_numerical_issues
    # xref: https://github.com/conda-forge/pandas-feedstock/issues/149
    {% set tests_to_skip = tests_to_skip + " or test_rolling_var_numerical_issues" %}             # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestFromArrays and test_constructor)" %}         # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestFromBreaks and test_constructor)" %}         # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestFromTuples and test_constructor)" %}         # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestClassConstructors and test_constructor)" %}  # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestStata and test_writer_117)" %}               # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestStata and test_convert_strl_name_swap)" %}   # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestStata and test_strl_latin1)" %}              # [s390x]
    {% set tests_to_skip = tests_to_skip + " or (TestStata and test_utf8_writer)" %}              # [s390x]
    # skip test_floordiv_axis0_numexpr_path python-pow
    # xref: https://github.com/pandas-dev/pandas/issues/54546
    {% set tests_to_skip = tests_to_skip + " or test_floordiv_axis0_numexpr_path" %}
    # skip windows tests which call _tz_localize_using_tzinfo_api - fails on CI but not when run on dev instance
    # OSError may be thrown by tzlocal on windows at or close to 1970-01-01
    #  see https://github.com/pandas-dev/pandas/pull/37591#issuecomment-720628241
    {% set tests_to_skip = tests_to_skip + " or TestDatetime64ArrayLikeComparisons or test_apply_out_of_range or TestNonNano or test_setitem_str_impute_tz" %} # [win]
    # test_scalar_unary triggers python 3.12 DeprecationWarning: Bitwise inversion '~' on bool is deprecated.
    {% set tests_to_skip = tests_to_skip + " or test_scalar_unary" %} # [py>=312]
    {% set extra_args = extra_args + ["-k", "not (" + tests_to_skip + ")", "--no-strict-data-files"] %}
    # use --no-strict-data-files
    # xref: https://github.com/pandas-dev/pandas/issues/54907
    - python -c "import pandas; pandas.test(extra_args={{ extra_args }})"

about:
  home: https://pandas.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
  description: |
    pandas is a Python package that provides fast, flexible, and expressive data structures
    designed to make working with "relational" or "labeled" data both easy and intuitive.
    It aims to be the fundamental high-level building block for doing practical, real world
    data analysis in Python. Additionally, it has the broader goal of becoming the most
    powerful and flexible open source data analysis / manipulation tool available in any
    language. It is already well on its way towards this goal.
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/pandas-docs/version/{{ version }}/index.html

extra:
  skip-lints:
    - has_run_test_and_commands
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
    - ryanskeith
