{% set version = "1.4.1" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 8db93ec98ac7cb5f8ac1420c10f5e3c43533153f253fe7fb6d891cf5aa2b80d2
  patches:
    - 00001_fix_missing_date_month_table.patch  # [linux and aarch64]

build:
  number: 1
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j${CPU_COUNT}" --no-use-pep517  # [unix]
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [not win]
  host:
    - python
    - pip
    - cython >=0.29.24
    - numpy   1.19  # [not (osx and arm64) and (py==38 or py==39)]
    - numpy   1.21  # [(osx and arm64) and (py==38 or py==39)]
    - numpy   1.21  # [not ppc64le and py==310]
    - setuptools >=51.0.0
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.8.1
    - pytz >=2020.1
    # Recommended dependencies to achieve large speedups
    # see https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#recommended-dependencies
    - numexpr >=2.7.1
    - bottleneck >=1.3.1

test:
  requires:
    - pip
    - hypothesis >=3.58
    - pytest >=6.0
    - pytest-xdist
    - package-testing
  imports:
    - pandas
  commands:
    - pip check
    - pytest -s -vv ${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/anaconda_package_tests



about:
  home: https://pandas.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/pandas-docs/stable/

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
    - WillAyd
    - simonjayhawkins
