{% set version = "0.24.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas/pandas-{{ version }}.tar.gz
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/pandas-{{ version }}.tar.gz
  sha256: 9bd9ef3e183b7b1ce90b7ab5e8672907cd73dc36f036fc6714f0e7a5f9852da0

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.12
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.*
    - pytz

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
