{% set version = "0.23.0" %}

package:
  name: pandas
  version: {{ version }}

source:
  git_url: https://github.com/pandas-dev/pandas
  git_tag: v{{ version }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
